### ISSUE TITLE
Error during execution slow tests

### ISSUE THREAD

**Issue by clagms** [INTO-CPS-Association/aurt#10]
I'm getting the following error when executing `URExampleTests`:
````
INFO:Tests:Compiling rigid-body dynamics...
DEBUG:aurt:Determining numerically the number of base parameters of 'rigid-body dynamics'...
DEBUG:aurt:No. of base parameters for 'rigid-body dynamics' at iteration 1: 12
...
DEBUG:aurt:No. of base parameters for 'rigid-body dynamics' at iteration 15: 38
INFO:aurt:For 'rigid-body dynamics' some terms were linearly dependent, thus the following parameter(s) were eliminated: True
INFO:Tests:Compile robot dynamics...
DEBUG:aurt:Determining numerically the number of base parameters of 'joint dynamics'...
DEBUG:aurt:No. of base parameters for 'joint dynamics' at iteration 1: 12
...
DEBUG:aurt:No. of base parameters for 'joint dynamics' at iteration 8: 30
INFO:aurt:'joint dynamics' consist entirely of linearly independent terms, thus no parameters were eliminated.
DEBUG:aurt:Determining numerically the number of base parameters of 'robot dynamics'...
DEBUG:aurt:No. of base parameters for 'robot dynamics' at iteration 1: 12
DEBUG:aurt:No. of base parameters for 'robot dynamics' at iteration 2: 18
...
DEBUG:aurt:No. of base parameters for 'robot dynamics' at iteration 22: 68
DEBUG:aurt:No. of base parameters for 'robot dynamics' at iteration 23: 68
INFO:aurt:For 'robot dynamics' some terms were linearly dependent, thus the following parameter(s) were eliminated: True
INFO:Tests:Calibrate
WARNING:aurt:66/31494 (0.21 %) samples are missing in this dataset.
DEBUG:aurt:Determining numerically the number of base parameters of 'rigid-body dynamics'...
DEBUG:aurt:No. of base parameters for 'rigid-body dynamics' at iteration 1: 12
DEBUG:aurt:No. of base parameters for 'rigid-body dynamics' at iteration 2: 18
DEBUG:aurt:No. of base parameters for 'rigid-body dynamics' at iteration 15: 38
INFO:aurt:For 'rigid-body dynamics' some terms were linearly dependent, thus the following parameter(s) were eliminated: True
DEBUG:aurt:Determining numerically the number of base parameters of 'robot dynamics'...
DEBUG:aurt:No. of base parameters for 'robot dynamics' at iteration 1: 12
...
DEBUG:aurt:No. of base parameters for 'robot dynamics' at iteration 23: 68
INFO:aurt:For 'robot dynamics' some terms were linearly dependent, thus the following parameter(s) were eliminated: True

Ran 1 test in 2943.664s
FAILED (errors=1)
Error
Traceback (most recent call last):
File "C:\srcctrl\github\aurt\tests\slow_tests\ur_example_tests.py", line 58, in test_ur5e_dh
api.calibrate(out_rd, data_file, gravity, params_out, calibration_out, plotting=False)
File "C:\srcctrl\github\aurt\aurt\api.py", line 53, in calibrate
params = rc.calibrate()
File "C:\srcctrl\github\aurt\aurt\robot_calibration.py", line 109, in calibrate
observation_matrix = self._observation_matrix(self.robot_data_calibration,
File "C:\srcctrl\github\aurt\aurt\robot_calibration.py", line 93, in _observation_matrix
obs_mat_j = self.robot_dynamics.observation_matrix_joint(j, states_num)
File "C:\srcctrl\github\aurt\aurt\robot_dynamics.py", line 76, in observation_matrix_joint
obs_mat_j_rbd = self.rigid_body_dynamics.observation_matrix_joint(j, states_num)
File "C:\srcctrl\github\aurt\aurt\linear_system.py", line 248, in observation_matrix_joint
observation_matrix_j[:, col_start:col_end] = self.observation_matrix_joint_parameters_for_joint(j, par_j, states_num)
File "C:\srcctrl\github\aurt\aurt\linear_system.py", line 265, in observation_matrix_joint_parameters_for_joint
observation_matrix_j_parj[:, nonzeros] = regressor_j_parj_nonzeros_fcn(*states_num).T[:, :, 0] # "[:, :, 0]" eliminates the last (excess) dimension
IndexError: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 7
````

**Comment by clagms** [comment]
Now running the test again and see if I can reproduce it.

**Comment by clagms** [comment]
It seems this is happening consistently on my machine. Got the error in 2 out of 2 runs.

**Comment by clagms** [comment]
Nevermind. This problem went away. I cannot reproduce. Might be the specific package dependencies...
